//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 			Abstract Transaction (type). This type cannot be instantiated.
 * 			WARNING: The "EndToEndId" field identifies the transaction. For auditing purposes, it is imperative that each transaction receives a unique Identifer.
 * 			Failure to adhere to this recommendation will cause loss of trace capabilities in subsequent payment information documents.
 * 			The implementor of this schema is responsible for defining a reliable mechanism, which gurantees unique Ids for each document over the lifetime of the system implementation.
 * 			
 * 
 * <p>Java class for CoreTransactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoreTransactionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Amount" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}AmountAndCurrencyType"/&gt;
 *         &lt;element name="Purpose" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}PurposeType"/&gt;
 *         &lt;element name="ExecutionDate" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}ISODateType"/&gt;
 *         &lt;element name="EndToEndId" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}ReferenceIdentificationType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoreTransactionType", propOrder = {
    "amount",
    "purpose",
    "executionDate",
    "endToEndId"
})
@XmlSeeAlso({
    CreditTransferTransaction.class,
    DirectDebitTransaction.class
})
public abstract class CoreTransactionType {

    @XmlElement(name = "Amount", required = true)
    protected AmountAndCurrencyType amount;
    @XmlElement(name = "Purpose", required = true)
    protected String purpose;
    @XmlElement(name = "ExecutionDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar executionDate;
    @XmlElement(name = "EndToEndId", required = true)
    protected String endToEndId;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountAndCurrencyType }
     *     
     */
    public AmountAndCurrencyType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountAndCurrencyType }
     *     
     */
    public void setAmount(AmountAndCurrencyType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the executionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExecutionDate() {
        return executionDate;
    }

    /**
     * Sets the value of the executionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExecutionDate(XMLGregorianCalendar value) {
        this.executionDate = value;
    }

    /**
     * Gets the value of the endToEndId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndToEndId() {
        return endToEndId;
    }

    /**
     * Sets the value of the endToEndId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndToEndId(String value) {
        this.endToEndId = value;
    }

}
