//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Credit Transfer Initiation (type)
 * 
 * <p>Java class for CreditTransferType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditTransferType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}CoreInitiationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InitPtyDebitor" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}InitPartyType"/&gt;
 *         &lt;element name="Transaction" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}CreditTransferTransaction" maxOccurs="5000"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditTransferType", propOrder = {
    "initPtyDebitor",
    "transaction"
})
public class CreditTransferType
    extends CoreInitiationType
{

    @XmlElement(name = "InitPtyDebitor", required = true)
    protected InitPartyType initPtyDebitor;
    @XmlElement(name = "Transaction", required = true)
    protected List<CreditTransferTransaction> transaction;

    /**
     * Gets the value of the initPtyDebitor property.
     * 
     * @return
     *     possible object is
     *     {@link InitPartyType }
     *     
     */
    public InitPartyType getInitPtyDebitor() {
        return initPtyDebitor;
    }

    /**
     * Sets the value of the initPtyDebitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitPartyType }
     *     
     */
    public void setInitPtyDebitor(InitPartyType value) {
        this.initPtyDebitor = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditTransferTransaction }
     * 
     * 
     */
    public List<CreditTransferTransaction> getTransaction() {
        if (transaction == null) {
            transaction = new ArrayList<CreditTransferTransaction>();
        }
        return this.transaction;
    }

}
