//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Direct Debit Initiation (type)
 * 
 * <p>Java class for DirectDebitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectDebitType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}CoreInitiationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LocalInstrument" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}LocalInstrumentCodeType"/&gt;
 *         &lt;element name="InitPtyCreditor" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}InitPtyCreditorType"/&gt;
 *         &lt;element name="Transaction" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}DirectDebitTransaction" maxOccurs="5000"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectDebitType", propOrder = {
    "localInstrument",
    "initPtyCreditor",
    "transaction"
})
public class DirectDebitType
    extends CoreInitiationType
{

    @XmlElement(name = "LocalInstrument", required = true)
    @XmlSchemaType(name = "string")
    protected LocalInstrumentCodeType localInstrument;
    @XmlElement(name = "InitPtyCreditor", required = true)
    protected InitPtyCreditorType initPtyCreditor;
    @XmlElement(name = "Transaction", required = true)
    protected List<DirectDebitTransaction> transaction;

    /**
     * Gets the value of the localInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link LocalInstrumentCodeType }
     *     
     */
    public LocalInstrumentCodeType getLocalInstrument() {
        return localInstrument;
    }

    /**
     * Sets the value of the localInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalInstrumentCodeType }
     *     
     */
    public void setLocalInstrument(LocalInstrumentCodeType value) {
        this.localInstrument = value;
    }

    /**
     * Gets the value of the initPtyCreditor property.
     * 
     * @return
     *     possible object is
     *     {@link InitPtyCreditorType }
     *     
     */
    public InitPtyCreditorType getInitPtyCreditor() {
        return initPtyCreditor;
    }

    /**
     * Sets the value of the initPtyCreditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitPtyCreditorType }
     *     
     */
    public void setInitPtyCreditor(InitPtyCreditorType value) {
        this.initPtyCreditor = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DirectDebitTransaction }
     * 
     * 
     */
    public List<DirectDebitTransaction> getTransaction() {
        if (transaction == null) {
            transaction = new ArrayList<DirectDebitTransaction>();
        }
        return this.transaction;
    }

}
