//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Direct Debit Transaction (type)
 * 
 * <p>Java class for DirectDebitTransaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectDebitTransaction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}CoreTransactionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OthrPtyDebitor" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}OthrPtyDebitorType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectDebitTransaction", propOrder = {
    "othrPtyDebitor"
})
public class DirectDebitTransaction
    extends CoreTransactionType
{

    @XmlElement(name = "OthrPtyDebitor", required = true)
    protected OthrPtyDebitorType othrPtyDebitor;

    /**
     * Gets the value of the othrPtyDebitor property.
     * 
     * @return
     *     possible object is
     *     {@link OthrPtyDebitorType }
     *     
     */
    public OthrPtyDebitorType getOthrPtyDebitor() {
        return othrPtyDebitor;
    }

    /**
     * Sets the value of the othrPtyDebitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link OthrPtyDebitorType }
     *     
     */
    public void setOthrPtyDebitor(OthrPtyDebitorType value) {
        this.othrPtyDebitor = value;
    }

}
