//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="5000"&gt;
 *         &lt;element name="CreditTransfer" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}CreditTransferType"/&gt;
 *         &lt;element name="DirectDebit" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}DirectDebitType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creditTransferOrDirectDebit"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElements({
        @XmlElement(name = "CreditTransfer", type = CreditTransferType.class),
        @XmlElement(name = "DirectDebit", type = DirectDebitType.class)
    })
    protected List<CoreInitiationType> creditTransferOrDirectDebit;

    /**
     * Gets the value of the creditTransferOrDirectDebit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditTransferOrDirectDebit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditTransferOrDirectDebit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditTransferType }
     * {@link DirectDebitType }
     * 
     * 
     */
    public List<CoreInitiationType> getCreditTransferOrDirectDebit() {
        if (creditTransferOrDirectDebit == null) {
            creditTransferOrDirectDebit = new ArrayList<CoreInitiationType>();
        }
        return this.creditTransferOrDirectDebit;
    }

}
