//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Initiating Direct Debit party (creditor) (type)
 * 
 * <p>Java class for InitPtyCreditorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitPtyCreditorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}InitPartyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CreditorId" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}CreditorIdType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitPtyCreditorType", propOrder = {
    "creditorId"
})
public class InitPtyCreditorType
    extends InitPartyType
{

    @XmlElement(name = "CreditorId", required = true)
    protected String creditorId;

    /**
     * Gets the value of the creditorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorId() {
        return creditorId;
    }

    /**
     * Sets the value of the creditorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorId(String value) {
        this.creditorId = value;
    }

}
