//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.catpay.domiu.konfipay.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.catpay.domiu.konfipay.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link CreditTransferType }
     * 
     */
    public CreditTransferType createCreditTransferType() {
        return new CreditTransferType();
    }

    /**
     * Create an instance of {@link DirectDebitType }
     * 
     */
    public DirectDebitType createDirectDebitType() {
        return new DirectDebitType();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyType }
     * 
     */
    public AmountAndCurrencyType createAmountAndCurrencyType() {
        return new AmountAndCurrencyType();
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link InitPartyType }
     * 
     */
    public InitPartyType createInitPartyType() {
        return new InitPartyType();
    }

    /**
     * Create an instance of {@link InitPtyCreditorType }
     * 
     */
    public InitPtyCreditorType createInitPtyCreditorType() {
        return new InitPtyCreditorType();
    }

    /**
     * Create an instance of {@link OthrPtyDebitorType }
     * 
     */
    public OthrPtyDebitorType createOthrPtyDebitorType() {
        return new OthrPtyDebitorType();
    }

    /**
     * Create an instance of {@link MandateDataType }
     * 
     */
    public MandateDataType createMandateDataType() {
        return new MandateDataType();
    }

    /**
     * Create an instance of {@link CreditTransferTransaction }
     * 
     */
    public CreditTransferTransaction createCreditTransferTransaction() {
        return new CreditTransferTransaction();
    }

    /**
     * Create an instance of {@link DirectDebitTransaction }
     * 
     */
    public DirectDebitTransaction createDirectDebitTransaction() {
        return new DirectDebitTransaction();
    }

}
