//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//


package de.catpay.domiu.konfipay.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Other Direct Debit party (debitor) (type)
 * 
 * <p>Java class for OthrPtyDebitorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OthrPtyDebitorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}PartyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MandateData" type="{urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3}MandateDataType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OthrPtyDebitorType", propOrder = {
    "mandateData"
})
public class OthrPtyDebitorType
    extends PartyType
{

    @XmlElement(name = "MandateData", required = true)
    protected MandateDataType mandateData;

    /**
     * Gets the value of the mandateData property.
     * 
     * @return
     *     possible object is
     *     {@link MandateDataType }
     *     
     */
    public MandateDataType getMandateData() {
        return mandateData;
    }

    /**
     * Sets the value of the mandateData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandateDataType }
     *     
     */
    public void setMandateData(MandateDataType value) {
        this.mandateData = value;
    }

}
