//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 06:29:04 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:windata:xsd:fsln:sdxi:sepa:de:ccft.1.3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.catpay.domiu.konfipay.dto;
